LetsFrameAdminBundle:
    resource: "@LetsFrameAdminBundle/Resources/config/routing.yml"
    prefix:   /

LetsFrameMainBundle:
    resource: "@LetsFrameMainBundle/Resources/config/routing.yml"
    prefix:   /

#Security Admin
login:
    pattern: /login
    defaults: {_controller: LetsFrameAdminBundle:Admin:login }
login_check:
    pattern: /login_check
logout:
    pattern: /logout

#imagine bundle pour redimensionner les images
_imagine:
    resource: .
    type:     imagine


# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
