LetsFrameAdminBundle_login:
    pattern:  /admin
    defaults: { _controller: LetsFrameAdminBundle:Admin:login }

LetsFrameAdminBundle_homepage:
    pattern:  /admin/accueil
    defaults: { _controller: LetsFrameAdminBundle:Admin:index }
