parameters:
#    lets_frame_admin.example.class: LetsFrame\AdminBundle\Example

services:
#    lets_frame_admin.example:
#        class: %lets_frame_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
