<?php

namespace LetsFrame\BiduleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BiduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BiduleRepository extends EntityRepository
{
    public function createQBfindAll()
    {
        return $this->createQueryBuilder('n');
    }

    public function findByImageId($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a
                FROM  LetsFrameBiduleBundle:Bidule a
                JOIN a.gallery g
                JOIN g.images i
                WHERE i.id = :id
                '
            )->setParameter('id',$id)
            ->getResult();
    }

}
