<?php

namespace LetsFrame\BiduleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BiduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BiduleRepository extends EntityRepository
{
    public function createQBfindAll()
    {
        return $this->createQueryBuilder('n');
    }
}
